name: 'Modular Android'
description: 'Builds Android Modules selectively'
inputs:
  for-all-modules:
    description: 'Gradle Task to run for all modules'
    required: true
    default: 'clean'
  for-each-module:
    description: 'Gradle Task to run for each module'
    required: true
    default: 'build'
runs:
  using: 'node12'
  main: 'index.js'
  args:
    - ${{ inputs.for-all-modules }}
    - ${{ inputs.for-each-module }}
